### ISSUE TITLE
Cannot read property 'PLAIN' of undefined in IOS

### ISSUE THREAD

**Issue by Ansalibrahim** [aksonov/react-native-xmpp#41]
The code is working fine on android. But in IOS simulator it shows some exception like :- 

> ExceptionsManager.js:62 Cannot read property 'PLAIN' of undefinedhandleException 
> @ ExceptionsManager.js:62handleError 
> @ InitializeJavaScriptAppEngine.js:120reportFatalError 
> @ error-guard.js:30guardedLoadModule 
> @ require.js:60_require 
> @ require.js:49(anonymous function) 
> @ require-0.js:1executeApplicationScript 
> @ debuggerWorker.js:20onmessage 
> @ debuggerWorker.js:38

**Comment by hoetmaaiers** [comment]
I am experiencing the same issue. It appears that this issue boils down to an unsupported architecture:

```
node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
```

**Comment by reformer** [comment]
@hoetmaaiers @Ansalibrahim  Hey do u resolved this issue?

**Comment by reformer** [comment]
I resolved this issue. This issue come because we can not fallow proper steps of installation of this package. Apart from this [https://github.com/aksonov/react-native-xmpp#getting-started](https://github.com/aksonov/react-native-xmpp#getting-started) i drag ..node_modules/react-native-xmpp/RNXMPP.xcodeproj in to my xcode project and set ENABLE_BITCODE to NO in xcode build settings.

**Comment by imrankhanjoya** [comment]
didn't work for me... Please help
